In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
data = np.arange(20).reshape(4,5).astype(np.float32)
print(data)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


In [ ]:
layer = tf.keras.layers.Dropout(rate=0.2, input_shape=(5,))
layer(data)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)>

In [ ]:
layer(data, training=True)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.  ,  1.25,  2.5 ,  0.  ,  5.  ],
       [ 6.25,  0.  ,  8.75, 10.  , 11.25],
       [12.5 ,  0.  , 15.  , 16.25, 17.5 ],
       [ 0.  , 20.  , 21.25,  0.  , 23.75]], dtype=float32)>