In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
cancer_dict = load_breast_cancer()

In [5]:
cancer_dict.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
print(cancer_dict.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [10]:
cancer_dict.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [8]:
cancer_feature_df = pd.DataFrame(cancer_dict.data, columns=cancer_dict.feature_names)

In [9]:
cancer_feature_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [10]:
from sklearn import preprocessing

x = cancer_feature_df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
cancer_feature_df = pd.DataFrame(x_scaled)
cancer_feature_df

0         1         2         3         4         5         6   \
0    0.521037  0.022658  0.545989  0.363733  0.593753  0.792037  0.703140   
1    0.643144  0.272574  0.615783  0.501591  0.289880  0.181768  0.203608   
2    0.601496  0.390260  0.595743  0.449417  0.514309  0.431017  0.462512   
3    0.210090  0.360839  0.233501  0.102906  0.811321  0.811361  0.565604   
4    0.629893  0.156578  0.630986  0.489290  0.430351  0.347893  0.463918   
..        ...       ...       ...       ...       ...       ...       ...   
564  0.690000  0.428813  0.678668  0.566490  0.526948  0.296055  0.571462   
565  0.622320  0.626987  0.604036  0.474019  0.407782  0.257714  0.337395   
566  0.455251  0.621238  0.445788  0.303118  0.288165  0.254340  0.216753   
567  0.644564  0.663510  0.665538  0.475716  0.588336  0.790197  0.823336   
568  0.036869  0.501522  0.028540  0.015907  0.000000  0.074351  0.000000   

           7         8         9   ...        20        21        22  \
0    0.731113  0.686364  0.605518  ...  0.620776  0.141525  0.668310   
1    0.348757  0.379798  0.141323  ...  0.606901  0.303571  0.539818   
2    0.635686  0.509596  0.211247  ...  0.556386  0.360075  0.508442   
3    0.522863  0.776263  1.000000  ...  0.248310  0.385928  0.241347   
4    0.518390  0.378283  0.186816  ...  0.519744  0.123934  0.506948   
..        ...       ...       ...  ...       ...       ...       ...   
564  0.690358  0.336364  0.132056  ...  0.623266  0.383262  0.576174   
565  0.486630  0.349495  0.113100  ...  0.560655  0.699094  0.520892   
566  0.263519  0.267677  0.137321  ...  0.393099  0.589019  0.379949   
567  0.755467  0.675253  0.425442  ...  0.633582  0.730277  0.668310   
568  0.000000  0.266162  0.187026  ...  0.054287  0.489072  0.043578   

           23        24        25        26        27        28        29  
0    0.450698  0.601136  0.619292  0.568610  0.912027  0.598462  0.418864  
1    0.435214  0.347553  0.154563  0.192971  0.639175  0.233590  0.222878  
2    0.374508  0.483590  0.385375  0.359744  0.835052  0.403706  0.213433  
3    0.094008  0.915472  0.814012  0.548642  0.884880  1.000000  0.773711  
4    0.341575  0.437364  0.172415  0.319489  0.558419  0.157500  0.142595  
..        ...       ...       ...       ...       ...       ...       ...  
564  0.452664  0.461137  0.178527  0.328035  0.761512  0.097575  0.105667  
565  0.379915  0.300007  0.159997  0.256789  0.559450  0.198502  0.074315  
566  0.230731  0.282177  0.273705  0.271805  0.487285  0.128721  0.151909  
567  0.402035  0.619626  0.815758  0.749760  0.910653  0.497142  0.452315  
568  0.020497  0.124084  0.036043  0.000000  0.000000  0.257441  0.100682  

[569 rows x 30 columns]

In [13]:
cancer_feature_df['mean perimeter'] = cancer_feature_df['mean perimeter']/cancer_feature_df['mean perimeter'].max()

In [26]:
cancer_feature_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0     0.639986      0.264257        0.651459   0.400240          0.11840   
1     0.731768      0.452393        0.705040   0.530188          0.08474   
2     0.700462      0.540988        0.689655   0.481008          0.10960   
3     0.406261      0.518839        0.411565   0.154378          0.14250   
4     0.721807      0.365071        0.716711   0.518593          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...      0.704218       0.349818         0.734873   
1                 0.05667  ...      0.693396       0.472547         0.632166   
2                 0.05999  ...      0.653996       0.515341         0.607086   
3                 0.09744  ...      0.413707       0.534921         0.393591   
4                 0.05883  ...      0.625416       0.336496         0.605892   

   worst area  worst smoothness  worst compactness  worst concavity  \
0    0.474612            0.1622             0.6656           0.7119   
1    0.459803            0.1238             0.1866           0.2416   
2    0.401740            0.1444             0.4245           0.4504   
3    0.133451            0.2098             0.8663           0.6869   
4    0.370240            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [17]:
cancer_feature_df['mean area'] = cancer_feature_df['mean area']/cancer_feature_df['mean area'].max()

In [18]:
cancer_feature_df['mean radius'] = cancer_feature_df['mean radius']/cancer_feature_df['mean radius'].max()

In [19]:
cancer_feature_df['mean texture'] = cancer_feature_df['mean texture']/cancer_feature_df['mean texture'].max()

In [21]:
cancer_feature_df['worst radius'] = cancer_feature_df['worst radius']/cancer_feature_df['worst radius'].max()

In [22]:
cancer_feature_df['worst texture'] = cancer_feature_df['worst texture']/cancer_feature_df['worst texture'].max()

In [23]:
cancer_feature_df['worst perimeter'] = cancer_feature_df['worst perimeter']/cancer_feature_df['worst perimeter'].max()

In [25]:
cancer_feature_df['worst area'] = cancer_feature_df['worst area']/cancer_feature_df['worst area'].max()

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X = cancer_feature_df
y = cancer_dict.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
from sklearn.svm import SVC

In [192]:
svm_classifier = SVC(kernel='poly', degree=5)

In [193]:
from sklearn.model_selection import GridSearchCV

In [194]:
search_dic = {'C': [0.01, 0.1, 1 , 8, 10 , 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]}

In [195]:
grid_search = GridSearchCV(svm_classifier, search_dic)

In [196]:
# grid_search.fit(X_train, y_train)
svm_classifier.fit(X_train, y_train)

SVC(degree=5, kernel='poly')

In [209]:
svm_classifier.intercept_

array([1.98037174])

In [197]:
grid_search.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [198]:
# prediction = grid_search.predict(X_test)
prediction = svm_classifier.predict(X_test) 

In [199]:
prediction

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [200]:
y_test

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [201]:
from sklearn.metrics import confusion_matrix, classification_report

In [202]:
print(confusion_matrix(y_test, prediction))

[[ 61   2]
 [  1 107]]


In [203]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98        63
           1       0.98      0.99      0.99       108

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171

