In [19]:
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from scipy import io
from sklearn.svm import SVC

In [20]:
# data = load_iris()
mat = io.loadmat("COIL20.mat")
X = mat["X"]
y = mat["Y"]
y = y[:, 0]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [22]:
# scale data before pca
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
data_pca = PCA(n_components=10)
pca_components = data_pca.fit(X_train)
X_train = pca_components.fit_transform(X_train)
# iris_features_after_pca_transform = pca_components.fit_transform(X_train)
X_test = pca_components.transform(X_test)

In [24]:
sum(pca_components.explained_variance_ratio_[:50])

0.6574672384362215

In [25]:
svc_clf = SVC(kernel="linear")
svc_clf.fit(X_train, y_train)

SVC(kernel='linear')

In [26]:
y_predict = svc_clf.predict(X_test)

In [27]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        17
           3       0.94      0.83      0.88        18
           4       1.00      1.00      1.00        21
           5       0.76      0.93      0.84        14
           6       1.00      1.00      1.00        18
           7       1.00      1.00      1.00        19
           8       1.00      1.00      1.00        21
           9       1.00      0.94      0.97        18
          10       1.00      1.00      1.00        15
          11       1.00      1.00      1.00        18
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00        21
          14       1.00      1.00      1.00        12
          15       1.00      1.00      1.00        16
          16       1.00      1.00      1.00        12
          17       1.00      1.00      1.00        21
          18       1.00    

In [28]:
import numpy as np

In [29]:
np.linalg.eig(np.array([[2,0], [0,2]]))

(array([2., 2.]),
 array([[1., 0.],
        [0., 1.]]))

In [31]:
X = np.array([[1,0], [0,1], [0, -1], [-1, 0]])
pca_mojtaba = PCA(n_components=2)
X_pca = pca_mojtaba.fit(X)
X_pca.explained_variance_ratio_

array([0.5, 0.5])